### ISSUE TITLE
Consistently prefix your functions with a prefix

### ISSUE THREAD

**Issue by mandiwise** [redacademy/unya-spring-2017#11]
You've added the `unya_` prefix to many of your functions, but please check your `extras.php` file and do this for all of them.

**Comment by rcass** [comment]
All the prefixes look good.
[Here](https://github.com/redacademy/unya-spring-2017/commit/0a5346021529c2d2a0426a8398d3727d9abb0644) is the commit for reference.
The formatting in that php files needs some work to make it more reasonable.

Also for the custom css you are adding, just small formatting fix to be done. Which is adding a space between the selector and the first curly brace.
