### ISSUE TITLE
Search not available in mobile or tablet view

### ISSUE THREAD

**Issue by sovetsch** [redacademy/unya-spring-2017#116]
### Overview
Search is not showing up on mobile or tablet views. The search only appears to display when stretching the width of the screen and going back to mobile.

### Tasks
- [x] Increase height of the search box to 56px, the search field to 32px, and the search text to 16px
- [x] Change search text to black (currently grey)

### Screenshot
<img width="507" alt="screen shot 2018-01-07 at 2 56 00 pm" src="https://user-images.githubusercontent.com/35045729/34655222-0457ddba-f3bb-11e7-8280-ac8b5ea2b3e7.png">

**Comment by tmclean85** [comment]
-Repositioned class toggle from its own script to an existing click handler. Multiple event listeners seem to have been causing conflicts. Seems to toggle fine now.
-Fix styling per above directions

Resolved under merge commit 4ad99a4
