### ISSUE TITLE
About Page - Reports panel not masking color and icon correctly

### ISSUE THREAD

**Issue by sovetsch** [redacademy/unya-spring-2017#118]
<img width="1065" alt="screen shot 2018-01-07 at 2 59 13 pm" src="https://user-images.githubusercontent.com/35045729/34655256-630ba04e-f3bb-11e7-9c0a-d2f8d77e42d1.png">

**Comment by tmclean85** [comment]
I don't see this issue locally or on the staging site. Perhaps it was fixed and the ticket left unmanaged?

**Comment by tmclean85** [comment]
Forgot about this. Merge commit c1ad834 should resolve.
