### ISSUE TITLE
Fix Headings on pages

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#119]
### Overview
When sidebar menu item is clicked, the auto scroll lands in the middle of heading. 

### Pages to edit:
- [x] Programs
- [x] Impact
- [x] News
- [x] Get Involved (Sidebar also needs to be updated to include Join Us)

**Comment by tmclean85** [comment]
Resolved with merge commit b6e53bf

**Comment by jesstice** [comment]
Nice! All works.
