### ISSUE TITLE
Footer & Instagram Updates

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#122]
#### Instagram
- [x] Instagram button leads to the UNYA location feed on Instagram, change this to go directly to UNYA’s Instagram page
- [x] Change Instagram heading text to “Get social with UNYA”

#### Footer
- [x] Add hyperlinks for both the phone number and address
- [x] We need to add a privacy policy here, to satisfy requirements to run Google Analytics on the site. Can we add a link in the “Contact Us” block for this, directly under the text that is already there? I’ve created a draft privacy policy page that we can link to.  
- [x] "I see that our Mailchimp account is connected through the Mailchimp for WP plugin, but it looks like it isn’t running the mailing list sign-up, or isn’t connected. The email sign-up should feed directly to our Mailchimp list please." - Client
- [x] Mobile: Add the footer at the bottom of the site so that it's static
- [x] Double check to see why phone number disappears on tablet... (screenshot below)

**Comment by jesstice** [comment]
@Coryjh85 were you able to get the link for the phone number working?

**Comment by sovetsch** [comment]
One last thing, can we keep the scroll position after the newsletter signup is complete. Currently it reloads to the top of the page which makes a user think it timed out. @tmclean85 @Coryjh85

**Comment by sovetsch** [comment]
Phone number also disappears on native browsers when I tested it on an iPhone7. See comment on the accordion issue.

**Comment by jesstice** [comment]
@sovetsch Is this still an issue?

**Comment by sovetsch** [comment]
Phone number is there, just the privacy policy is cut off on a iPhone 7 and I can't seem to scroll to it either.

![img_65c731bbd2f7-1](https://user-images.githubusercontent.com/35045729/36495028-c620013e-16e8-11e8-8ce2-b78a53df501c.jpeg)
![img_5ba03c1ced43-1](https://user-images.githubusercontent.com/35045729/36495050-d7105656-16e8-11e8-913f-e9b94b922017.jpeg)

**Comment by sovetsch** [comment]
@jesstice, unfortunately, the newsletter signup still jumps to the top of the page and it has some weird glitch on the checkbox. See video I sent on Slack
