### ISSUE TITLE
Program Page Fixes

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#126]
#### Main Page:
- [x] Add a pre-footer, drop in from Impact page
- [x] Images for individual programs:
  - [x] Remove gap between logo and text (shows up on larger screens)
  - [x] Make sure drop shadow is removed (this task is in the site-wide CSS bugs)
  - [x] Remove the gradient on default state, only show up on hover
- [x] Calendar: text for events fun into the next box... what can we do about this?
   ((Trevor: Seems to occur due to them having concatenated two longer words with a foreslash: 'Fitness/kickboxing', so text is unable to wrap. Can be mitigated by adding spaces appropriately. Please review and advise, will action if still desired.))
- [x] Program Names: "There has been a slight change to how program areas are named and organized, based on feedback from staff on the focus of programs. I’ve changed this in the menus, but this will need to be changed in the program area banners as well. I’m not sure if there is a need to change the slugs as well (not sure what they do), or if this complicates things significantly for you." - Client
  ((Trevor: Slugs do not need to change. Headers have been updated to reflect new categories, anchor/url pairs remain unchanged))
- [x] Mobile: "Navigating to the program areas from the drop-down menu automatically opens these sections with the screen jumping to the bottom of the screen, which works when there aren’t many individual programs, but in sections where there are more programs, it ends up cutting off the heading and some of the programs. Potentially a problem if/when additional programs are added, as users may miss programs higher up on the page." - Client
((Trevor: Please review and test fix on merge commit 1a24bc0 ))

#### Individual Page:
- [x] "Program kindly funded by" => remove this
- [x] Phone # and email can shift to the right side
- [x] Pre-footer
  - [x] Remove "Get involved..." header
  - [x] "Contact..." should be the new header at 32px
  - [x] All contact info should be links
  - [x] Troubleshoot: Problems with text colour and layout in Firefox (see screenshot in comments)
- [x] Align photo to the top of the div
- [x] Tablet/Mobile: Remove second photo

**Comment by jesstice** [comment]
<img width="1623" alt="screenshot 030" src="https://user-images.githubusercontent.com/19242967/34909900-84cf4d72-f85f-11e7-806f-61323511dbec.png">

**Comment by sovetsch** [comment]
**Main page:**

- [x] Desktop: program thumbnails stretch and squish on resize
<img width="781" alt="screen shot 2018-01-30 at 7 01 05 pm" src="https://user-images.githubusercontent.com/35045729/35603049-3694c148-05f0-11e8-8252-1fae22421656.png">
<img width="375" alt="screen shot 2018-01-30 at 7 01 16 pm" src="https://user-images.githubusercontent.com/35045729/35603050-36af3b7c-05f0-11e8-87bd-ab61a091a3c7.png">

**Individual Program Page:**
- [x] Desktop: Image needs to retain the same height as program activities when resized. And also aligned to the top of the div.
<img width="809" alt="screen shot 2018-01-30 at 7 03 38 pm" src="https://user-images.githubusercontent.com/35045729/35603082-69a9a01c-05f0-11e8-8527-9cae80a2b06b.png">

- [x] Desktop: I believe we discussed removing the logo box in the prefooter. Same issue on mobile and for leadership individual page.
<img width="1174" alt="screen shot 2018-01-30 at 7 05 54 pm" src="https://user-images.githubusercontent.com/35045729/35603117-9dd9a2f6-05f0-11e8-9a66-7b5c8318d78d.png">

- [x] Desktop: Resource thumbnails squished and padding non-existent.
<img width="967" alt="screen shot 2018-01-30 at 7 06 10 pm" src="https://user-images.githubusercontent.com/35045729/35603152-c4cff3ce-05f0-11e8-9e54-6f897c4d6020.png">

- [x] Mobile : Remove the second photo. Same for leadership individual page.
<img width="400" alt="screen shot 2018-01-30 at 7 08 00 pm" src="https://user-images.githubusercontent.com/35045729/35603180-ea7d8816-05f0-11e8-86cc-d4b29324cc2e.png">

- [x] Prefooter CTA needs to consistent as mentioned previously.
 
@Coryjh85 @jesstice @tmclean85

**Comment by tmclean85** [comment]
Do we want to eliminate the sponsor logo box from the program footer then? Another option would be conditionally rendering it if there is a sponsor, and not rendering if there is no sponsor. Let me know.

**Comment by sovetsch** [comment]
Let's leave it out. In conversation with them, they said that most programs don't have clear-cut sponsors per say. That was an assumption on the UX part.

Thank you for that idea though!

**Comment by tmclean85** [comment]
No problem, on it!

**Comment by tmclean85** [comment]
Please review footer and advise, there was no design for a footer without the logo box obviously so I did some dev design.

**Comment by sovetsch** [comment]
The footer looks great the way you did it!
The resources still appear funky, check the follow link: http://unya.cp.academy.red/programs/leadership/

@tmclean85

**Comment by tmclean85** [comment]
I trimmed the excerpt text a little further, but if a post is given a really long title the text may still crowd. Should I remove the excerpt?

Also, are the images distorted? They don't appear to be to me but I don't have the greatest eye for these things sometimes.

**Comment by sovetsch** [comment]
Yeah lets remove the excerpt as these titles are ridiclously long.

And yeah the become really distorted as the window width decrease, can we do a fill instead of stretch or so. Example below of what happens to it.

<img width="411" alt="screen shot 2018-01-31 at 11 40 22 pm" src="https://user-images.githubusercontent.com/35045729/35666847-744d2408-06e0-11e8-8156-5ac3c35f7b17.png">
<img width="692" alt="screen shot 2018-01-31 at 11 40 16 pm" src="https://user-images.githubusercontent.com/35045729/35666848-7472215e-06e0-11e8-9bdc-656a066b9937.png">
<img width="1045" alt="screen shot 2018-01-31 at 11 40 10 pm" src="https://user-images.githubusercontent.com/35045729/35666849-749c1324-06e0-11e8-9bc6-3a369cdc0344.png">

**Comment by tmclean85** [comment]
Oh got it. Yep, I'll take care of that.

**Comment by sovetsch** [comment]
Thanks!

**Comment by tmclean85** [comment]
Removed excerpt at desktop and addressed squashing issue with merge commit ce2166d

Solution isn't optimal. There is a range from about 850 to 800px until the tablet breakpoint where the images crowd off the side of the viewport a little. Due to having to account for programs that have both two and three resources rendering in that section, CSS-only solutions won't correct this. It isn't likely to be seen by users, however to remedy will require a more laborious programatic solution using jQuery.

**Comment by sovetsch** [comment]
Okay, lets leave it for now, if they complain we can always throw more time at that. Thanks for trying!

**Comment by jesstice** [comment]
Looks like this is all done for now.
