### ISSUE TITLE
Adjust size of right margin across site

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#127]
### Overview
The issue is that currently, when you resize the site the content gets squished at a certain point before you get to tablet. It looks terrible... We can experiment with this but it seems like the easiest solution might be to adjust the right margin to be % based.

**Comment by sovetsch** [comment]
Still open!

**Comment by Coryjh85** [comment]
i changed the right margin to 10%, think its better, but maybe double check after next deploy

**Comment by jesstice** [comment]
Is this completed @Coryjh85?
