### ISSUE TITLE
Impact Page Fixes

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#128]
#### Main Impact Page
- [x] Banner height for success stories and volunteer section needs to be increased
- [x] Menu: 
  - [x] Add volunteer stories to side menu
  - [x] Selecting Statistics from the top menu jumps down to Testimonials rather than Statistics section.
- [x] Testimonials: 
  - [x] decrease font weight to 300 => looks a bit too chunky right now
  - [x] need a line break for the name
- [x] Stats:
  - [x] Title missing
  - [x] Buttons overlapping image
  - [x] Add arrows
- [x] tablet: pre-footer text and button should be side by side
- [x] mobile: Success story / volunteer name text too large, longer names get cut off (still happens)
  - [x] Centre names in portrait
- [ ] mobile: stats image larger than section (see comment below for image)
- [ ] stats: remove previous and next text by the arrows (screenshot below)

#### Individual Impact pages
- [x] photos distorted
- [x] sidebar menu: "success stories" should lead back to the impact page
- [x] Tablet (Portrait orientation): the photo converts to the banner midway through, but the smaller photo still shows up (Screenshot below)
- [x] Mobile: For both the individual success stories and volunteer stories, text goes right to the left of the page, making it a bit difficult to read. Add padding.
- [x] Mobile: remove image from banner image (currently photo shows up)

#### Screenshots
![screenshot 023](https://user-images.githubusercontent.com/19242967/34909936-3d9b84ec-f860-11e7-8dc4-82e677d0b3b0.PNG)

**Comment by sovetsch** [comment]
Just found this skewed image issue
<img width="1432" alt="screen shot 2018-01-29 at 2 31 49 pm" src="https://user-images.githubusercontent.com/35045729/35538028-4a2a0820-0501-11e8-980f-13a4a5b34915.png">
<img width="1244" alt="screen shot 2018-01-29 at 2 34 16 pm" src="https://user-images.githubusercontent.com/35045729/35538100-86da7c78-0501-11e8-876a-d44eb82dd947.png">

**Comment by jesstice** [comment]
@Coryjh85  Example of previous and next text that needs to be removed.
![screenshot_2018-02-22-00-25-42](https://user-images.githubusercontent.com/19242967/36527564-11377bc4-1767-11e8-9a2e-dedf6ff9d6bd.png)
