### ISSUE TITLE
CTA Buttons have serious bugs on several pages

### ISSUE THREAD

**Issue by sovetsch** [redacademy/unya-spring-2017#153]
Pages impacted for missing button: Impact, Programs
Page impacted by double line: News 
Both Desktop and mobile have these issues.

<img width="1339" alt="screen shot 2018-01-31 at 11 30 32 pm" src="https://user-images.githubusercontent.com/35045729/35666412-cf5a9bf2-06de-11e8-818f-5667790920d7.png">

Can we just make sure all the CTA's are consistent, of all the items on the site that is literally the one thing I care most about as the CTA's consistency will dramatically impact conversion. Same font-size and font-weight, same button shadow across all pages. Sorry for being picky about that!

@Coryjh85 @tmclean85

**Comment by tmclean85** [comment]
CTA issues resolved with merge commit cbf86c8

I'm not sure what the double line issue refers to. The News page does not share either of the CTA banners that are in play on the above pages. Is the issue with the Media Inquiries pre-footer?

**Comment by sovetsch** [comment]
Sorry I meant the Get Involved page.

**Comment by sovetsch** [comment]
The Get Involved has a similar CTA at the bottom with longer text but the styling of the text and button should definitely be the same as the other CTA's

**Comment by tmclean85** [comment]
Oh I see it now. I'm just out right now but I'll push a fix as soon as I'm home.

**Comment by jesstice** [comment]
Looks like this is completed!
