### ISSUE TITLE
Mop-up items as per client

### ISSUE THREAD

**Issue by tmclean85** [redacademy/unya-spring-2017#159]
### Impact Page
- [x] Volunteers doesn't appear on secondary menu
- [x] Volunteers doesn’t support line breaks/paragraphs. It looks like these are identical to the youth features (success stories), aside from this one aspect. Please change to reflect the Success Stories template, allowing for line breaks.
### News Page
- [x] Remove quotes appending to single news story featured quote section
- [x] "We need to be able to include links and headings within body text" (??)
- [x] On single internal news post page, move tags to bottom of news story, above footer

### Page Template (what even is this?)
- [x] "Add padding to the left and right sides of this on desktop – text currently goes right to the edge of the window"

### Media Inquiries
- [x] Contact info should be:
         1618 East Hastings Street
         604-379-5068
         communications@unya.bc.ca
         Footer
     Address should be:
     1618 East Hastings Street

### Categories Archive
- [x] Refactor hard-coded image to pull from page's featured image. Style if needed.

**Comment by tmclean85** [comment]
### Impact Page
- [ ] Volunteers doesn't appear on secondary menu
- [ ] Volunteers doesn’t support line breaks/paragraphs. It looks like these are identical to the youth features (success stories), aside from this one aspect. Please change to reflect the Success Stories template, allowing for line breaks.
### News Page
- [ ] Remove quotes appending to single news story featured quote section
- [ ] "We need to be able to include links and headings within body text" (??)

**Comment by tmclean85** [comment]
Resolved News Page items on merge commit feb5521

**Comment by tmclean85** [comment]
Resolved Categories Archive item on merge commit f46f2e9

**Comment by jesstice** [comment]
@Coryjh85 Did you set up the page template? Can you edit the padding?

**Comment by jesstice** [comment]
Dealt with padding on custom template.
