### ISSUE TITLE
Resource Images Distorting

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#175]
## Overview
__Note from client:__ Differences in how these show up on the Native Youth Centre page, and on individual program pages:
    • Everywhere EXCEPT mobile: The thumbnails are working well (not distorting) on the Native Youth Centre page, but are distorting on the program pages – can these be adjusted to reflect how they behave on the NYC page?
    • Mobile: Native Youth Centre page resource thumbnails aren’t showing up (Android) or are very distorted (iPhone). They look great on the programs page, can this be reflected on the NYC page as well?

## Tasks
- [ ] Fix Programs image distortion on mobile
- [ ] NYC resources styling

**Comment by tmclean85** [comment]
I don't see any distortion on the Programs images until mobile, at tab/dt they appear to keep their size. There's a little distortion at mobile which should be easily fixed.

On the NYC page, the resources don't seem to be getting any tablet-width styling, and at mobile the slider appears quite broken. I can look into this in the back end of the week.

**Comment by jesstice** [comment]
I think this is a bit out of date. We actually removed the carousel on the Programs page at mobile cause it was fucking up.
