### ISSUE TITLE
Privacy Policy Link Broken

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#176]
## Issue
Privacy policy link is broken.

**Comment by jesstice** [comment]
@Coryjh85 Are you still working on this? It still isn't working.

**Comment by tmclean85** [comment]
Link still broken. What is the intent with this? Should it link to an external resource? A PDF? Do we need to implement a privacy policy page?

**Comment by jesstice** [comment]
It links to a new page, which has already been created. The link just doesn't seem to be working on the main site, although it works on our staging.

**Comment by jesstice** [comment]
Looks like this is working now!
