### ISSUE TITLE
News Categories images not displaying

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#179]
## Overview
Images not displaying.
<img width="1087" alt="screen shot 2018-04-08 at 10 14 06 pm" src="https://user-images.githubusercontent.com/19242967/38480370-2e7298b8-3b7a-11e8-9017-e3406e1af7da.png">

**Comment by jesstice** [comment]
@Coryjh85 / @tmclean85 - I could use your help with this one. Where are the images coming from?

**Comment by tmclean85** [comment]
All good now, they needed to update "Featured Image" on the categories-archive page template.
