### ISSUE TITLE
Images on Windows 10 are blurry

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#180]
## Overview
Program thumbnail images are blurry.
![windows10chrome](https://user-images.githubusercontent.com/19242967/38480392-51d07a46-3b7a-11e8-8db1-f4f1f3068668.JPG)

**Comment by tmclean85** [comment]
Images appear blurry on osx as well. I don't think these are all new assets either so must be a formatting issue. I'll do some tinkering in-browser to see if there's a CSS solution.

![screen shot 2018-04-10 at 12 31 48 pm](https://user-images.githubusercontent.com/26736454/38579246-41e61266-3cbb-11e8-86cc-958cd1fd7452.png)
