### ISSUE TITLE
Create Categories page, Taxonomy Archive page

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#39]
- [ ] Look up ways to implement this
- [ ] Create a categories page
- [ ] Create a taxonomy archive page

- http://www.wpbeginner.com/plugins/how-to-add-taxonomy-images-in-wordpress/

**Comment by sovetsch** [comment]
@tmclean85 there is an alignment issue with the single line category. Can we make sure the text is vertical-align: middle

**Comment by tmclean85** [comment]
I wasn't 100% sure what was meant by this, but I think I fixed it with commit 307a340

**Comment by sovetsch** [comment]
All good that was me being way too picky. All good on that one!
