### ISSUE TITLE
Write CSS that prevents image proportions from being distorted

### ISSUE THREAD

**Issue by mandiwise** [redacademy/unya-spring-2017#6]
See screenshot:

<img width="788" alt="screen shot 2017-06-22 at 12 59 39 pm" src="https://user-images.githubusercontent.com/1518780/27453274-babeb352-574a-11e7-9bd3-d8c2851b8eb0.png">

**Comment by selikem** [comment]
It seems the image distortion is being caused by the flex-basis rule on the image-wrapper.  Removing it fixed the shape of the image wrapper (made it circular), which fixed the image distortion.
