### ISSUE TITLE
Site-wide CSS bug review and squash

### ISSUE THREAD

**Issue by tmclean85** [redacademy/unya-spring-2017#83]
## All / Nav / Footer
- [x] Mobile/Tablet hamburger menu needs right margin **DONE**
- [ ] Fix CSS for tablet view footer (see image in comments below)
- [ ] **Top Nav: add padding to search box (currently touches donate button)** **See note in comments
- [ ] Remove **all** drop shadows! => Change to 1px outline
- [ ] Fix resource CSS => look at the Invision prototype and copy it

## Front Page
- [ ] desktop: image overlay issues in Safari
- [X] desktop: slider banner slightly shorter than others
- [ ] desktop: images squished
- [ ] desktop: banner text squishes on resize, change width
- [X] tablet: slider banner text not centered **DONE**
- [ ] tablet: "Read more" should be buttons
- [ ] tablet: Leadership heading is off (see image in comment below)
- [ ] mobile: slider banner images squished
- [X] mobile: learn more arrows not centered with text **DONE**

## About Page
- [x] reports not properly styled at any width **DONE**
- [ ] some fonts incorrect
- [x] tablet- history section too crowded **DONE**
- [x] mobile: Vision and mission should always be visible, and philosophy of care should accordion **DONE**

## Programs Page
- [x] Programs page mobile: check out our programming banner text too large **DONE**

## Impact Page
Moved to #128 

## Native Youth Center
Move to #129

## News
Moved to #130

## Get Involved
Moved to #131
- [x] desktop: "Please email info@unya.bc.ca for additional job opportunities, or to be added to our email list" shows twice just above the footer **DONE RND 3**
- [x] tablet: "Donate" header improperly positioned **DONE RND 3**
- [x] tablet: No styling for Employment or Volunteer sections **DONE RND 3**

## Search
- [ ] Search results: change hard coded image to dynamic post image (Cory fixed?)

**Comment by jesstice** [comment]
### About Page - Leadership heading on tablet view:
<img width="368" alt="screen shot 2017-12-17 at 10 27 57 am" src="https://user-images.githubusercontent.com/19242967/34082534-12ac17f2-e315-11e7-9fa6-8154abac95b7.png">

**Comment by jesstice** [comment]
### Tablet View - Footer
<img width="387" alt="screen shot 2017-12-17 at 10 34 33 am" src="https://user-images.githubusercontent.com/19242967/34082578-e71f17a0-e315-11e7-885d-18d7cd58f85a.png">

Should be like this:
<img width="492" alt="screen shot 2017-12-17 at 10 34 50 am" src="https://user-images.githubusercontent.com/19242967/34082580-f5031876-e315-11e7-822b-3ea5b932f878.png">

**Comment by jesstice** [comment]
### Native Youth Center - Call to Action banner
<img width="386" alt="screen shot 2017-12-17 at 10 51 56 am" src="https://user-images.githubusercontent.com/19242967/34082735-7147dfb4-e318-11e7-840d-ce56e6456f78.png">

**Comment by jesstice** [comment]
### Impact - Stats Image on Mobile
<img width="260" alt="screen shot 2017-12-17 at 11 05 59 am" src="https://user-images.githubusercontent.com/19242967/34082809-6c2c16b0-e31a-11e7-8169-22e9ba68c525.png">

**Comment by jesstice** [comment]
### Impact - Pre-Footer on Mobile
<img width="267" alt="screen shot 2017-12-17 at 11 08 44 am" src="https://user-images.githubusercontent.com/19242967/34082835-d503f8c4-e31a-11e7-9536-c969e6cb6764.png">

**Comment by jesstice** [comment]
### Update Main Nav Bar
When rotating from portrait to landscape in tablet view, there's a lot of jankiness in the nav. Make sure that there should only be 2 rows for the menu items.
