### ISSUE TITLE
Testimonials section CSS, Remove from Accordion (Tablet)

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#92]
## Overview
Testimonials should be available in view on tablet view.

## Tasks
- [ ] Remove from Accordion
- [ ] Decrease text width

Current:
<img width="384" alt="screen shot 2017-12-17 at 10 39 54 am" src="https://user-images.githubusercontent.com/19242967/34082631-adf47294-e316-11e7-8042-a0bc8b3458e1.png">

Design:
<img width="496" alt="screen shot 2017-12-17 at 10 40 58 am" src="https://user-images.githubusercontent.com/19242967/34082637-d3325e7c-e316-11e7-91e3-3a34b48869df.png">

**Comment by tmclean85** [comment]
Resolves with merge commit f88c147
